code --install-extension christian-kohler.path-intellisense
code --install-extension cjhowe7.laravel-blade
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dawhite.mustache
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension espresso3389.unixtime-converter
code --install-extension fabianlauer.vs-code-xml-format
code --install-extension heaths.vscode-guid
code --install-extension jcbuisson.vue
code --install-extension jchannon.csharpextensions
code --install-extension justusadam.language-haskell
code --install-extension Leopotam.csharpfixformat
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension minhthai.vscode-todo-parser
code --install-extension mjmcloug.vscode-elixir
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.resharper9-keybindings
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension reflectiondm.classynaming
code --install-extension ryu1kn.partial-diff
code --install-extension selfrefactor.niketa-theme
code --install-extension sysoev.vscode-open-in-github
code --install-extension vscodevim.vim
